import torch
from typing import Optional, Literal
class KMeans:
    def __init__(self,
                 n_clusters:int,
                 max_iter:Optional[int]=1000,
                 batchsize:Optional[int]=100,
                 init_method:Optional[Literal["random", "kmeans++"]]="kmeans++",
                 dist_method:Optional[Literal["euclidean", "cosine", "manhattan"]]="euclidean",
                 random_state:Optional[int]=None,
                 epsilon:Optional[float]=1e-8) -> None: ...
    def fit_predict(self, x: torch.Tensor) -> torch.Tensor: ...
    def predict(self, x: torch.Tensor) -> torch.Tensor: ...
    def fit(self, x: torch.Tensor) -> None: ...
    def init_centers(self, x: torch.Tensor) -> None: ...
    def update_centers(self, x: torch.Tensor) -> None: ...
    def update_labels(self, x: torch.Tensor) -> None: ...
    def pairwise_distance(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor: ...
    def compute_distance_matrix(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor: ...
    def get_centers(self) -> torch.Tensor: ...